# Generated by Django 4.0.2 on 2022-02-14 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daje_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 9, 42, 30, 814642)),
        ),
    ]
