# Generated by Django 4.0.2 on 2022-02-14 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_daje_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='daje_joined',
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 9, 45, 53, 905530)),
        ),
    ]
